# Generated by Django 2.0.2 on 2018-02-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180226_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
