# Generated by Django 2.0.2 on 2018-02-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180226_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(to='restaurant.MenuItem'),
        ),
    ]
