# Generated by Django 2.0.2 on 2018-03-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyAmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='supplyamt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.MenuItem'),
        ),
        migrations.AddField(
            model_name='supplyamt',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.SupplyItem'),
        ),
    ]
