# Generated by Django 2.0.2 on 2018-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20180301_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items_are_available',
            field=models.BooleanField(default=False),
        ),
    ]
