# Generated by Django 2.0.2 on 2018-03-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_order_items_are_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_time', models.CharField(default='0', max_length=4)),
            ],
        ),
    ]
